// Copyright (c) 2026 Sub Rosa contributors
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as sdk from "./index.js";

const EXPECTED_EXPORTS = [
  "SubRosaPaginationError",
  "ASSET_FIXTURES",
  "AssetConfigError",
  "ACTIVE_ROUND_STATUSES",
  "ERROR_ROUND_STATUSES",
  "KeeperStatusClient",
  "KeeperStatusTimeoutError",
  "MAINNET_ARTIFACTS",
  "MAINNET_CONFIRM_PHRASE",
  "MAINNET_DEPLOY_MIN_XLM_STROOPS",
  "MAINNET_MICRO_MAX_ESCROW",
  "MAINNET_MIN_FEE_RESERVE_STROOPS",
  "MAX_AUDITOR_BLOB_BYTES",
  "MAX_CIPHERTEXT_BYTES",
  "RECEIPT_EVENT_ERROR_CODES",
  "RECEIPT_VERSION",
  "ROUND_CONTRACT_ERRORS",
  "ROUND_CONTRACT_ERRORS_BY_NAME",
  "RoundContract",
  "RoundErrors",
  "StatusApiError",
  "StatusJsonParseError",
  "SubRosaAssetValidationError",
  "SubRosaClient",
  "SubRosaClientConfigError",
  "SubRosaMissingReturnValueError",
  "SubRosaNetworkMismatchError",
  "SubRosaNetworkPassphraseMismatchError",
  "SubRosaPreflightError",
  "SubRosaSessionMismatchError",
  "SubRosaSubmitError",
  "SubRosaTimeoutError",
  "SubRosaTransactionError",
  "TERMINAL_ROUND_STATUSES",
  "assertMainnetConfirmed",
  "assertMicroAmounts",
  "assertReadinessForExecute",
  "classifyRoundStatus",
  "contractErrorCode",
  "createOzChannelsSubmitter",
  "createOzChannelsSubmitterFromEnv",
  "createSacBalanceReader",
  "defaultMainnetReadinessInput",
  "describeNetworkPassphraseMismatch",
  "evaluatePreflight",
  "fetchContractWasmHash",
  "fetchKeeperStatus",
  "formatReadinessReport",
  "getRoundContractError",
  "hasBlockingFailures",
  "isActiveRoundStatus",
  "isErrorRoundStatus",
  "isKeeperRoundActive",
  "isKeeperRoundSettlementPending",
  "isKeeperRoundTerminal",
  "isRoundContractErrorRetryable",
  "isTerminalRoundStatus",
  "nativeXlmSacId",
  "networkDisplayName",
  "networkFingerprint",
  "networkPassphrasesMatch",
  "normalizeRoundId",
  "normalizeSorobanContractId",
  "parseMicroStroops",
  "parseReceipt",
  "redactReceipt",
  "redactUrlUserinfo",
  "roundStatusLabel",
  "runMainnetReadiness",
  "runMicroRunnerGate",
  "expectedRoundEventSequence",
  "serializeReceipt",
  "tryDecodeBase64",
  "tryDecodeHex",
  "validateAssetConfig",
  "validateAssetConfigs",
  "validateEncryptedBlob",
  "validateContractNetwork",
  "validatePasskeySession",
  "verifyReceipt",
  "verifyReceiptEvents",
  "verifySettledRoundProof",
];

describe("SDK public API snapshot", () => {
  it("should match the expected named exports", () => {
    const actual = Object.keys(sdk).sort();
    const expected = [...EXPECTED_EXPORTS].sort();
    assert.deepEqual(actual, expected);
  });
});
