// Copyright (c) 2026 Sub Rosa contributors
export {
  keepRound,
  closeRound,
  voidIfStale,
  discoverRoundIds,
  parseRoundIdSpec,
  watchRound,
  waitForRound,
  errorName,
  errorMatches,
  type KeeperDeps,
  type KeeperResult,
  type CloseResult,
  type VoidResult,
  type WatchTickResult,
  type KeeperLogger,
  type SkipRecord,
} from "./keeper.js";
export {
  createSettlementGuard,
  describeSettlementSkip,
  evaluateSettle,
  evaluateVoid,
  expectedWinner,
  readSettlementView,
  settleRefunds,
  voidRefunds,
  VOID_GRACE_SECONDS,
  type ClearingRuleTag,
  type ContractDecision,
  type ContractSkipEvent,
  type ContractSkipReason,
  type DuplicateSkipEvent,
  type GuardBidderState,
  type GuardSkipRecord,
  type RoundSettlementView,
  type SettlementAction,
  type SettlementCheck,
  type SettlementGuard,
  type SettlementGuardEntry,
  type SettlementGuardStatus,
  type SettlementPlan,
  type SettlementSkipEvent,
} from "./settlement-guard.js";
export {
  buildKeeperDryRunSummary,
  decideKeeperDryRunAction,
  parseKeeperRunConfig,
  planDryRunCheckpoint,
  DRY_RUN_PHASE_STEP,
  type KeeperDryRunCheckpoint,
  type KeeperDryRunDecision,
  type KeeperDryRunOptions,
  type KeeperDryRunPhase,
  type KeeperDryRunReader,
  type KeeperDryRunSummary,
  type KeeperRunConfig,
} from "./dry-run.js";
export {
  checkpointBindingMismatch,
  checkpointHasStep,
  planCheckpointRollback,
  planCheckpointStep,
  readCheckpointFile,
  CHECKPOINT_SKIP_STEPS,
  CHECKPOINT_VERSION,
  DEFAULT_CHECKPOINT_PATH,
  KeeperCheckpointError,
  KeeperCheckpointMismatchError,
  KeeperCheckpointStore,
  STEP_SATISFIED_BY_STATUS,
  type CheckpointVerification,
  type KeeperCheckpoint,
  type KeeperCheckpointFile,
  type KeeperCheckpointStoreOptions,
  type KeeperStep,
  type ResumableCheckpoint,
  type TransactionHashStatus,
  type TransactionHashVerifier,
  type WatchCheckpoint,
} from "./checkpoint.js";
export {
  createStatusServer,
  createStatusHandler,
  withGracefulShutdown,
  bigintReplacer as statusBigintReplacer,
  type StatusServerConfig,
  type StatusServerHandle,
} from "./status-server.js";
export {
  buildKeeperStatus,
  buildRoundStatus,
  checkHealth,
  guardSkipIndicator,
  type BuildStatusSource,
  type BuildRoundStatusArgs,
  type StatusReader,
  type RoundStatus,
  type SettlementIndicator,
  type RoundStatusView,
  type KeeperServiceHealth,
  type KeeperStatusResponse,
} from "./status.js";
export {
  resumeCheckpoint,
  runWatchLoop,
  type ResumeCheckpointParams,
  type RunWatchLoopParams,
} from "./watch-loop.js";
